/**
  * SinePiano
  * 
  * Dan Ellis, dpwe@ee.columbia.edu, 2010-01-22
  *
  * This sketch lets you play notes or chords using the computer keyboard as a piano keyboard.
  * The 'Z' key is C4, and running up the bottom row to '/' plays a little over an octave, 
  * with the black notes coming from the row above.
  *
  * The actual sounds are generated by instances of SineWave, created in response to each 
  * keypress.  The amplitude decays with each successive buffer, giving a nice exponential 
  * decay sound.
  * 
*/

class MyNote implements AudioSignal{
     private float freq;
     private float level;
     private float alph;
     private SineWave sine;
     
     MyNote(float pitch, float amplitude) // <--!!!!NOTE MY COMPUTER HAS NO SOUND NOW
     {
         freq = pitch;
         level = amplitude;
         sine = new SineWave(freq, level, out.sampleRate());
         alph = 0.9;  // Decay constant for the envelope
         out.addSignal(this);
     }

     void updateLevel()
     {
         // Called once per buffer to decay the amplitude away
         level = level * alph;
         sine.setAmp(level);
         
         // This also handles stopping this oscillator when its level is very low.
         if (level < 0.01) {
             out.removeSignal(this);
         }
         // this will lead to destruction of the object, since the only active 
         // reference to it is from the LineOut
     }
     
     void generate(float [] samp)
     {
         // generate the next buffer's worth of sinusoid
         sine.generate(samp);
         // decay the amplitude a little bit more
         updateLevel();
     }
     
    // AudioSignal requires both mono and stereo generate functions
    void generate(float [] sampL, float [] sampR)
    {
        sine.generate(sampL, sampR);
        updateLevel();
    }

}
